before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends latexmk
  texlive-fonts-extra texlive-fonts-recommended texlive-latex-base texlive-latex-extra
  texlive-latex-recommended
script:
- mkdir _build
- latexmk -pdf -outdir=_build senior_thesis_proposal.tex
deploy:
  provider: releases
  skip_cleanup: true
  on:
tags: true
#Markdown lint:
- proselint README.md
