# Site settings
title: Andrew C. Everitt
email: everitta@allegheny.edu
url: https://andreweveritt.com
description: "Computer Science Student"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Andrew C. Everitt

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
  #  url: https://twitter.com/
  - title: linkedin
    url: https://www.linkedin.com/in/andrew-everitt/
  - title: bitbucket
    url: https://bitbucket.org/everitt_andrew/
  - title: github
    url: https://github.com/everitt-andrew

# Build settings
markdown: kramdown
permalink: pretty
