# Site settings
title: Zachary J. Leonardo
email: zachleonardo15@gmail.com
url: https://zacharyleonardo.com
description: "Aspiring Software Engineer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Zachary J. Leonardo

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ZachLeonardoAC?lang=en
  - title: linkedin
    url: https://www.linkedin.com/in/zacharyleonardo/
  - title: bitbucket
    url: https://bitbucket.org/leonardoz15/
  - title: github
    url: https://github.com/leonardoz15

# Build settings
markdown: kramdown
permalink: pretty
